# Generated by Django 5.2 on 2025-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=512)),
                ('image', models.ImageField(upload_to='static/.../')),
                ('author', models.TextField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
